title: Nativv Studios
markdown: kramdown
url: "nativvstudios.github.io"
baseurl: ""

# for atom feed
author:
  name: Whyherro
  email: whyherro@nativvstudios.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
