title: Nativv Studios
markdown: kramdown
url: "nativvstudios.github.io"
baseurl: ""
repository: nativvstudios/nativvstudios.github.io

sitehome: "/index.html"

navigation:
- text: Home
  url: "/"
- text: Life
  url: "/life.html"
- text: Tutorials
  url: "/tutorials.html"   
- text: Portfolio
  url: "/portfolio.html"
- text: Links
  url: "/links.html"



linklist:
  - title: Buy me a Tea ❤️
    url: https://ko-fi.com/nativvstudios
  - title: Twitter 
    url: 'https://twitter.com/whyherro1'
  - title: Github
    url:  'https://github.com/nativvstudios'
  - title: Dev.to
    url: https://dev.to/nativvstudios
  - title: Gitlab
    url: https://gitlab.com/whyherro1
  # - title: facebook
  #   url: 'https://example.com/@jekyllrb'
  # - title: instagram
  #   url: 'https://example.com/@jekyllrb'
  # - title: linkedin
  #   url: 'https://example.com/@jekyllrb'
  # - title: youtube
  #   url: 'https://example.com/@jekyllrb'
  # - title: twitch
  #   url: 'https://example.com/@jekyllrb'
  # - title: telegram
  #   url: 'https://example.com/@jekyllrb'
  # - title: whatsapp
  #   url: 'https://example.com/@jekyllrb'
  # - title: discord
  #   url: 'https://example.com/@jekyllrb'
  # - title: slack
  #   url: 'https://example.com/@jekyllrb'
  - title: Email
    url: mailto:whyherro@nativvstudios.com

portfolio:

- item: PlacesNB
  screenshot: "assets/uploads/placesnb.png"
  description: "PlacesNB is your comprehensive guide to outdoor adventure in New Brunswick. We're passionate about showcasing the natural beauty and recreational opportunities throughout our beautiful province."
  url: "https://www.placesnb.ca"
- item: NativvShare
  screenshot: "assets/uploads/NativvShare.png"
  description: "NativvShare is an image hosting service that functions in the way Imgur used to before it migrated to being a social network. NativvShare is for internal use only and registrations will never be open."
  url: "https://www.nativvstudios.io"
- item: Aurora Css
  description: "A lightweight, modern CSS framework focused on creating elegant, responsive interfaces with glass morphism effects, fluid animations, and dark/light mode support."
  url: "/aurora.html"
  slides:
    - image: "assets/uploads/aurora.gif"
      description: "A lightweight, modern CSS framework focused on creating elegant, responsive interfaces with glass morphism effects, fluid animations, and dark/light mode support."
    - image: "assets/uploads/aurora.gif"
      description: "A lightweight, modern CSS framework focused on creating elegant, responsive interfaces with glass morphism effects, fluid animations, and dark/light mode support."

- item: JekyllxBulma
  description: "JekyllxBulma is a Jekyll theme built ontop of the Bulma CSS Framework"
  url: "https://nativvstudios.com/jekyllxbulma"
  slides:
    - image: "assets/uploads/jekyllxbulma.png"
      description: "JekyllxBulma is a Jekyll theme built ontop of the Bulma CSS Framework"
- item: Jekyll Bootstrap Theme
  description: "Jekyll theme built ontop of the Bootstrap 5 Framework"
  url: "https://www.nativvstudios.com/bootstrap-jekyll-dark/"
  slides:
    - image: "assets/uploads/jekyllboot.png"
      description: "Jekyll theme built ontop of the Bootstrap 5 Framework"
- item: From Ether
  description: "From Ether is a captivating story-driven 2D pixel art RPG where you discover your origins from the mythical element of creation, Ether. Guided by the Ether, you realize your destined role in this timeline: to overcome the encroaching evil. Unravel the mysteries of your existence and fulfill your purpose in a beautifully crafted world, blending compelling narrative and nostalgic visuals."
  url: ""
  slides:
    - image: "assets/uploads/FromEtherLogo.png"
      description: "From Ether is a captivating story-driven 2D pixel art RPG where you discover your origins from the mythical element of creation, Ether. Guided by the Ether, you realize your destined role in this timeline: to overcome the encroaching evil. Unravel the mysteries of your existence and fulfill your purpose in a beautifully crafted world, blending compelling narrative and nostalgic visuals."


# for atom feed
author:
  name: "Whyherro"
  email: whyherro@nativvstudios.com

disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: "nativvstudios"

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

jekyll_compose:
  default_front_matter:
    drafts:
      layout: post
      categories:
      comments: true
    posts:
      layout: post
      categories:
      comments: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
# exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]

